[SECTION_1]
;動作モード(1:本番(マーカテキスト送信),　2:テスト(ファイル書き込みのみ))
MODE=1

; ============================================================
;UI_REC_TYPEは対象の炉種で指定する記載内容を変換する
;焼準⇒HNR
;焼入⇒HQ
;ピット⇒PIT
;バッチ（美原）⇒BATCH
;バッチ（岐阜）⇒BATCH_G
;球状化⇒SA(ここはまだ未作成)
; ============================================================
UI_REC_TYPE=PIT
; ============================================================
;焼準・焼入焼戻炉限定、対象炉の名前を入れる
;CSV取得するためのファイル名検索に使用
;使用炉名
;美原
;焼準
;SGNR-1・SGNR-2・SGNR-3・SGNR-4・SGNR-5
;焼入焼戻
;SQGT-2・SQGT-3・SQGT-4

;加西
;焼準
;SKGNR-1・SKGNR-2・SKGNR-3
;SA
;SKGSA-1

;岐阜
;焼準
;SGNR-1・SGNR-2・SGNR-3
;焼入焼戻
;SQGT-1・SQGT-2
;SA
;SGSA-1
; ============================================================
;RONAME="SGNR-1"

; ============================================================
;アップデートに必要な共有にあるファイルやフォルダーを配置したフォルダーとそのパス
;32bit:\\192.168.203.202\Sprint\SendMarkerText\
;64bit:\\192.168.203.202\Sprint\SendMarkerText64bit\
; ============================================================
DEFAULT_SHARE_DIR=\\192.168.203.202\Sprint\SendMarkerText\
LEGACY_SHARE_DIR=\\192.168.203.202\Sprint\SendMarkerText

; ============================================================
;Accessファイルのパス
;ACCESS_FILEは確認者や作業者の社員番号確認に必要
;下記で固定
; ============================================================
ACCESS_FILE=\\192.168.203.202\Sprint\社員番号.accdb

; ============================================================
;ACCESS_FILE_2は1H4Hチェックの際に送信されるデータ場所

;ピット炉:\\192.168.203.202\Sprint\PIT_1H4Hチェック履歴.accdb
;バッチ炉:\\192.168.203.202\Sprint\BATCH_1H4Hチェック履歴.accdb
;焼準炉:\\192.168.203.202\Sprint\焼準_1H4Hチェック履歴.accdb
;焼入焼戻炉:\\192.168.203.202\Sprint\焼入焼戻_1H4Hチェック履歴.accdb

;岐阜
;焼準:\\192.168.203.202\Sprint\SGNR-1岐阜_py_1H4Hチェック.accdb→\\192.168.203.202\Sprint\焼準_岐阜_1H4Hチェック履歴.accdb
;SA:\\192.168.203.202\Sprint\SA_岐阜_1H4Hチェック履歴.accdb
;焼入焼戻:\\192.168.203.202\Sprint\焼入焼戻_岐阜_1H4Hチェック履歴.accdb
;バッチ炉:\\192.168.203.202\Sprint\BATCH_岐阜_1H4Hチェック履歴.accdb

;加西
;焼準:\\192.168.203.202\Sprint\焼準_加西_1H4Hチェック.accdb
;SA:\\192.168.203.202\Sprint\SA_加西_1H4Hチェック履歴.accdb

;上記に「_test」を追加したaccessファイルは本番のデータベースへの影響を避ける試験運用のため
; ============================================================
ACCESS_FILE_2=\\192.168.203.202\Sprint\PIT_1H4Hチェック履歴_test.accdb
;ACCESS_FILE_2=\\192.168.203.202\Sprint\焼準_1H4Hチェック履歴.accdb
;ACCESS_FILE_2=C:\Users\User\Downloads\焼準_1H4Hチェック履歴.accdb

; ============================================================
;記録計のグループ指定
;同一IPの場合はグループを変えることで指定した炉名の画面に送信することが出来る
;現在の上限は4つまで
; ============================================================
RECORDER_GROUP1=1
RECORDER_GROUP2=2
RECORDER_GROUP3=3
RECORDER_GROUP4=4

; ============================================================
;記録計のIPアドレスとポート番号
;RECORDER_TYPEにはUI_REC_TYPEに入力した炉種を入力

;RECORDER_IP_ADRESSには送信したい記録計のIPアドレスを入力
;入力個数は対象にしたい炉の個数分
;美原のピットでは
;PG-1~PG-5・SQ-1~SQ-3・油槽(同一のが二つ)で10個分用意する
;----------------------------------------
;美原
;ピット
;記録計1:192.168.203.55
;記録計2:192.168.203.151
;記録計3:192.168.203.152
;バッチ
;NG-1:192.168.203.153
;TG-2:192.168.203.154
;焼準
;NR-1:192.168.203.134
;NR-2:192.168.203.138
;NR-3:192.168.203.131
;NR-4:192.168.203.130
;NR-5:192.168.203.132
;焼入焼戻
;GT-2:192.168.203.120
;GT-3:192.168.203.128
;GT-4:192.168.203.123

;加西
;焼準
;NR-1:
;NR-2:
;NR-3:

;岐阜
;焼準
;NR-1:192.168.243.140
;NR-2:不明
;NR-3:不明
;焼入焼戻炉
;GT-1:不明
;GT-2:不明
;バッチ
;記録計1:192.168.243.152
;記録計2:192.168.243.153
;SA:不明

;ポートについては記録計での変更は無し「RECORDER_PORT=502」
; ============================================================
RECORDER_TYPE1=PIT
RECORDER_IP_ADRESS1=192.168.203.55
RECORDER_PORT1=502

RECORDER_TYPE2=PIT
RECORDER_IP_ADRESS2=192.168.203.55
RECORDER_PORT2=502

RECORDER_TYPE3=PIT
RECORDER_IP_ADRESS3=192.168.203.55
RECORDER_PORT3=502

RECORDER_TYPE4=PIT
RECORDER_IP_ADRESS4=192.168.203.55
RECORDER_PORT4=502

RECORDER_TYPE5=PIT
RECORDER_IP_ADRESS5=192.168.203.55
RECORDER_PORT5=502

RECORDER_TYPE6=PIT
RECORDER_IP_ADRESS6=192.168.203.55
RECORDER_PORT6=502

RECORDER_TYPE7=PIT
RECORDER_IP_ADRESS7=192.168.203.55
RECORDER_PORT7=502

RECORDER_TYPE8=PIT
RECORDER_IP_ADRESS8=192.168.203.55
RECORDER_PORT8=502

RECORDER_TYPE9=PIT
RECORDER_IP_ADRESS9=192.168.203.55
RECORDER_PORT9=502

RECORDER_TYPE10=PIT
RECORDER_IP_ADRESS10=192.168.203.55
RECORDER_PORT10=502
; ============================================================
;記録計送信用CSVフォルダ監視先
;CSV_FOLDER
;美原:\\192.168.203.202\RecordCSV_out\
;加西:\\192.168.203.202\RecordCSV_out_k\
;岐阜:\\192.168.203.202\RecordCSV_out_g\
;で上記に変更
;試験運用:\\192.168.203.202\RecordCSV_out_test\
;で影響を最小限にする

;CSV_FILEはRE +指定した炉名

;----------------------------------------
;以下はピットやバッチなどの炉名を指定していない炉

;美原のピットバッチは複数対象
;ピット
;CSV_FILE1=REPG-1.csv
;CSV_FILE2=REPG-3.csv
;CSV_FILE3=RESQ-1.csv
;CSV_FILE4=RE油槽.csv
;CSV_FILE5=REPG-2.csv
;CSV_FILE6=RESQ-3.csv
;CSV_FILE7=RE油槽.csv
;CSV_FILE8=REPG-4.csv
;CSV_FILE9=REPG-5.csv
;CSV_FILE10=RESQ-2.csv

;バッチ
;CSV_FILE1=RENG-1.csv
;CSV_FILE2=RETG-2.csv

;岐阜のバッチ炉も同様
;CSV_FILE1=REBH-1岐阜.csv
;CSV_FILE2=REBH-2岐阜.csv
;CSV_FILE3=REBT-1岐阜.csv
;CSV_FILE4=REBT-2岐阜.csv
;CSV_FILE5=REBT-3岐阜.csv

;SA炉
;CSV_FILE1=RESGSA-1.csv

;加西
;SA炉
;CSV_FILE1=RESKGSA-1.csv
; ============================================================
CSV_FOLDER1=\\192.168.203.202\RecordCSV_out_test\
CSV_FILE1=REPG-1.csv

; ============================================================
;シーケンサ送信用CSVフォルダ監視先
;;CSV_FOLDER
;美原:\\192.168.203.202\CSV_out\
;加西:\\192.168.203.202\CSV_out_k\
;岐阜:\\192.168.203.202\CSV_out_g\
;試験運用:\\192.168.203.202\CSV_out_test\
;を指定することで影響を避ける

;CSV_FILEはWS +指定した炉名.csv

;岐阜のバッチ炉
;CSV_FILE6=BH-1岐阜.csv
;CSV_FILE7=BH-2岐阜.csv
;CSV_FILE8=BT-1岐阜.csv
;CSV_FILE9=BT-2岐阜.csv
;CSV_FILE10=BT-3岐阜.csv
; ============================================================
CSV_FOLDER2=\\192.168.203.202\CSV_out_test\
CSV_FILE2=REPG-1.csv


; ============================================================
;記録計への送信内容設定後のグループ指定および書き込み指示前のSleep時間(単位:ミリ秒)
; ============================================================
WAIT_TIME1=500

; ============================================================
;CSVファイルから記録計への連続送信時のウェイト時間
; ============================================================
WAIT_TIME2=0